### PR TITLE
feat: add subtitle & authors

### PR DESCRIPTION
**Pull request by maxigimenez**
hd

### CODE REVIEW

**Comment by maxigimenez** [comment]
BTW this can be tested here https://guides-checklyhq-com-git-feat-og-image-subtitle-authors.checkly.vercel.app

**Comment by tnolet** [comment]
@maxigimenez I'm getting a `0` in the lead text when checking 
https://guides-checklyhq-com-git-feat-og-image-subtitle-authors.checkly.vercel.app/posts/generating-pdfs/ using https://metatags.io/

image

**Comment by tnolet** [comment]
And some leading `**` and the `0` on the article https://guides-checklyhq-com-git-feat-og-image-subtitle-authors.checkly.vercel.app/posts/basics-playwright-intro/

image

**Comment by maxigimenez** [comment]
@tnolet I already fixed the `0` issue, check going to the image directly for example (https://og-image-git-feat-add-subtitle-authors.checkly.vercel.app/**Generating%20PDFs**.png?md=1&subTitle=&authors=Giovanni%20Rago&authorsImg=https://github.com/ragog.png?size=50). There might be cached version.

**Review by tnolet — CHANGES_REQUESTED** [review]
I left two questions. Seems some rendering is a bit off

**Comment by maxigimenez** [comment]
Also the `**What is playwright?` happens on production already https://og-image.theheadless.dev/**What%20is%20Playwright?**.png?theme=light&md=1&fontSize=120px. I will check this on another PR

**Review by tnolet — APPROVED** [review]
LGTM

**Pull request merged**
