### PR TITLE
feat: add checkly base images + query param options

### PR DESCRIPTION
**Pull request by ndom91**
Added the following four base images:

image

Where `template: 'site' | 'learn' | 'docs' | 'blog'`. The other primary query parameter options are: `titleText`, `subtitleText` and `breadcrumbsText`.

The filename is irrelevant.

Examples:
- Web Playground: https://og-image-git-ndom91-add-base-img-types-checkly.vercel.app/
- Learn: https://og-image-git-ndom91-add-base-img-types-checkly.vercel.app/site.png?titleText=API%20Monitoring&template=learn&fontSize=50px&subtitleText=Understanding%20what%20a%20script%20does&breadcrumbsText=Checkly%20Learn
- Blog: https://og-image-git-ndom91-add-base-img-types-checkly.vercel.app/site.png?titleText=API%20Monitoring&template=blog&fontSize=50px&subtitleText=Understanding%20what%20a%20script%20does

Of course they need some cleaning up, but works decently well so far. 

### Todo:
- [x] clean up alignment, font size, etc, etc.
- [x] allow a secondary image to be embedded on `blog` type (like in the example screenshot above)

# UPDATE

So as mentioned above, there are a few important query parameters, as you can see in the examples below.

1. `template`: `'site' | 'learn' | 'docs' | 'blog'`
2. `breadcrumbsText`: `string` (`docs` and `learn` type only!)
3. `titleText`: `string`
4. `subtitleText`: `string`
5. `image`: `string` (`blog` type only! URI Encoded URL to image)
6. `width`: `number` (`blog` type only! Applys to custom image)
7. `height`: `number` (`blog` type only! Applys to custom image)

Cleaned up the web playground / demo for this as well: https://og-image-git-ndom91-add-base-img-types-checkly.vercel.app/

Also swapped out puppeteer for playwright :) 

### 1. `blog` Template (with custom image): 
image
> https://og-image-git-ndom91-add-base-img-types-checkly.vercel.app/blog.png?titleText=Hello%2520World&template=blog&fontSize=75px&subtitleText=This%20is%20a%20very%20long%20piece%20of%20text%20and%20I%20wonder%20how%20much%20more%20I%20can%20do&image=https%3A%2F%2Fimgur.com%2FtK1ipxq.png&height=250&width=380

### 2. `blog` Template (without custom image defined - displaying fallback image): 
image
> https://og-image-git-ndom91-add-base-img-types-checkly.vercel.app/blog.png?titleText=Hello%2520World&template=blog&fontSize=75px&subtitleText=This%20is%20a%20very%20long%20piece%20of%20text%20and%20I%20wonder%20how%20much%20more%20I%20can%20do

### 3. `learn` Template: 
image

> https://og-image-git-ndom91-add-base-img-types-checkly.vercel.app/blog.png?titleText=Hello%2520World&template=learn&fontSize=100px&subtitleText=This%20is%20a%20very%20long%20piece%20of%20text%20and%20I%20wonder%20how%20much%20more%20I%20can%20do&breadcrumbsText=Checkly%20%2F%20Learnings%20%2F%20Post%201

### 4. `docs` Template: 
image

> https://og-image-git-ndom91-add-base-img-types-checkly.vercel.app/docs.png?titleText=Scraping%2520%2526%2520asserting%2520on%2520a%2520page&subtitleText=Any%2520standard%2520Node.js%2520script%2520that%2520successfully%2520finishes%2520an%2520execution%2520is%2520a%2520valid%252C%2520passing%2520browser%2520check.&breadcrumbsText=Checkly%2520Docs%2520%252F%2520Headless%2520Automation%2520%252F%2520Basics%2520Debugging&template=docs&fontSize=50px

### 5. `site` Template: 
image

> https://og-image-git-ndom91-add-base-img-types-checkly.vercel.app/blog.png?titleText=Hello%2520World&template=site&fontSize=100px&subtitleText=This%20is%20a%20very%20long%20piece%20of%20text%20and%20I%20wonder%20how%20much%20more%20I%20can%20do

### CODE REVIEW

**Comment by ndom91** [comment]
Check out the "UPDATED" section of the original PR comment above for more details. Otherwise, I've cleaned up the repo a bunch, removed all sorts of unnecessary files and edited the README, package.json, etc. for our use-case. 

Minus any design tweaks that you guys may want, this should be good to go!

**Review by maxigimenez — APPROVED** [review]
LGTM 👍

**Comment by ndom91** [comment]
Some examples with long truncated text:

https://og-image-git-ndom91-add-base-img-types-checkly.vercel.app/docs.png?template=site&titleText=Scraping%2520%2526%2520asserting%2520on%2520a%2520page%20Scraping%2520%2526%2520asserting%2520on%2520a%2520page%2526more%20pages%20Scraping%2520%2526%2520asserting%2520on%2520a%2520page%20whatabout%20this&subtitleText=Any%2520standard%2520Node.js%2520script%2520that%2520successfully%2520finishes%2520an%2520execution%2520is%2520a%2520valid%252C%2520passing%2520browser%2520check.%20Any%2520standard%2520Node.js%2520script%2520that%2520successfully%2520finishes%2520an%2520execution%2520is%2520a%2520valid%252C%2520passing%2520browser%2520check.Any%2520standard%2520Node.js%2520script%2520that%2520successfully%2520finishes%2520an%2520execution%2520is%2520a%2520valid%252C%2520passing%2520browser%2520check.&breadcrumbsText=Checkly%2520Docs%2520%252F%2520Headless%2520Automation%2520%252F%2520Basics%2520Debugging&fontSize=50px

image

**Review by tnolet — APPROVED** [review]
Looks great. LGTM

**Comment by orcunilbeyli** [comment]
Perfect!

**Review by orcunilbeyli — APPROVED** [review]
Purrrfect!

**Pull request merged**
